language: rust
os:
- windows
- linux
sudo: false
cache: cargo
script:
- cargo build --release
- cargo test --verbose --all
deploy:
  provider: releases
  api_key: $deploy_key
  file:
  - target/release/scaffold-rs
  - target/release/scaffold-rs.exe
  skip_cleanup: true
  on:
    repo: Eonm/scaffold-rs
    all_branches: true
tags: true
