use clap::{Arg, App, SubCommand};

pub fn build_cli() -> App<'static, 'static> {
    App::new("scaffold-rs")
        .version("1.0.0")
        .author("Eonm <eon.mathis@gmail.com>")
        .about("Create files and directories recursively")
        .subcommand(SubCommand::with_name("scaffold")
            .arg(Arg::with_name("template")
               .short("t")
               .long("template-path")
               .value_name("FILE")
               .required(true)
               .help("Path of template file")
               .takes_value(true))
            .arg(Arg::with_name("display")
                .short("d")
                .long("display")
                .help("Display template content")
                .takes_value(false))
            .arg(Arg::with_name("dry_run")
                .long("dry-run")
                .help("Only displays created path (files and directories won't be created)")
                .takes_value(false))
            .arg(Arg::with_name("verbosity")
                .short("v")
                .help("Increase verbosity")
                .takes_value(false)))
}
